// This file is automatically generated by qtc from "about.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/about.qtpl:1
package templates

//line templates/about.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/about.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/about.qtpl:1
func StreamTitle(qw422016 *qt422016.Writer) {
	//line templates/about.qtpl:1
	qw422016.N().S(`
<title>About the Highway</title>
`)
//line templates/about.qtpl:3
}

//line templates/about.qtpl:3
func WriteTitle(qq422016 qtio422016.Writer) {
	//line templates/about.qtpl:3
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/about.qtpl:3
	StreamTitle(qw422016)
	//line templates/about.qtpl:3
	qt422016.ReleaseWriter(qw422016)
//line templates/about.qtpl:3
}

//line templates/about.qtpl:3
func Title() string {
	//line templates/about.qtpl:3
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/about.qtpl:3
	WriteTitle(qb422016)
	//line templates/about.qtpl:3
	qs422016 := string(qb422016.B)
	//line templates/about.qtpl:3
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/about.qtpl:3
	return qs422016
//line templates/about.qtpl:3
}

//line templates/about.qtpl:5
func StreamContent(qw422016 *qt422016.Writer) {
	//line templates/about.qtpl:5
	qw422016.N().S(`
<article>
	<h1>About the Highway</title>
	<br />
	<img src="image/construction.gif" />
</article>
`)
//line templates/about.qtpl:11
}

//line templates/about.qtpl:11
func WriteContent(qq422016 qtio422016.Writer) {
	//line templates/about.qtpl:11
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/about.qtpl:11
	StreamContent(qw422016)
	//line templates/about.qtpl:11
	qt422016.ReleaseWriter(qw422016)
//line templates/about.qtpl:11
}

//line templates/about.qtpl:11
func Content() string {
	//line templates/about.qtpl:11
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/about.qtpl:11
	WriteContent(qb422016)
	//line templates/about.qtpl:11
	qs422016 := string(qb422016.B)
	//line templates/about.qtpl:11
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/about.qtpl:11
	return qs422016
//line templates/about.qtpl:11
}
