// Code generated by qtc from "admin.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/admin.qtpl:1
package templates

//line templates/admin.qtpl:1
import "github.com/kipukun/sanic_highway/model"

//line templates/admin.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/admin.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/admin.qtpl:4
type AdminMainPage struct {
	User *model.User
}

//line templates/admin.qtpl:9
func (p *AdminMainPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/admin.qtpl:9
	qw422016.N().S(`
<title>highway administration</title>
`)
//line templates/admin.qtpl:11
}

//line templates/admin.qtpl:11
func (p *AdminMainPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/admin.qtpl:11
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/admin.qtpl:11
	p.StreamTitle(qw422016)
//line templates/admin.qtpl:11
	qt422016.ReleaseWriter(qw422016)
//line templates/admin.qtpl:11
}

//line templates/admin.qtpl:11
func (p *AdminMainPage) Title() string {
//line templates/admin.qtpl:11
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/admin.qtpl:11
	p.WriteTitle(qb422016)
//line templates/admin.qtpl:11
	qs422016 := string(qb422016.B)
//line templates/admin.qtpl:11
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/admin.qtpl:11
	return qs422016
//line templates/admin.qtpl:11
}

//line templates/admin.qtpl:14
func (p *AdminMainPage) StreamContent(qw422016 *qt422016.Writer) {
//line templates/admin.qtpl:14
	qw422016.N().S(`
<h1>hello `)
//line templates/admin.qtpl:15
	qw422016.E().S(p.User.Username)
//line templates/admin.qtpl:15
	qw422016.N().S(`</h1>
<h2>operations</h2>
<p>ingest will take in a .txt consisting of one fname per line.
 it just ignores duplicates</p>
<form action="/api/ingest" enctype="multipart/form-data" method="post">
	<input type="file" name="file">
	<input type="submit" value="ingest">
</form>
<p>export will export the db as a compressed JSON file, for easier importing later on.</p>
<form action="/api/export" enctype="multipart/form-data" method="post">
	<input type="submit" value="export">
</form>
`)
//line templates/admin.qtpl:27
}

//line templates/admin.qtpl:27
func (p *AdminMainPage) WriteContent(qq422016 qtio422016.Writer) {
//line templates/admin.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/admin.qtpl:27
	p.StreamContent(qw422016)
//line templates/admin.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line templates/admin.qtpl:27
}

//line templates/admin.qtpl:27
func (p *AdminMainPage) Content() string {
//line templates/admin.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/admin.qtpl:27
	p.WriteContent(qb422016)
//line templates/admin.qtpl:27
	qs422016 := string(qb422016.B)
//line templates/admin.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/admin.qtpl:27
	return qs422016
//line templates/admin.qtpl:27
}
