// This file is automatically generated by qtc from "circle.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/circle.qtpl:1
package templates

//line templates/circle.qtpl:1
import "github.com/kipukun/sanic_highway/model"

//line templates/circle.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/circle.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/circle.qtpl:4
type CirclePage struct {
	Circle []model.Circle
	Ero    []model.Eroge
}

//line templates/circle.qtpl:12
func (p *CirclePage) StreamTitle(qw422016 *qt422016.Writer) {
	//line templates/circle.qtpl:12
	qw422016.N().S(`
<title>`)
	//line templates/circle.qtpl:13
	qw422016.E().S(p.Circle[0].Name)
	//line templates/circle.qtpl:13
	qw422016.N().S(`</title>
`)
//line templates/circle.qtpl:14
}

//line templates/circle.qtpl:14
func (p *CirclePage) WriteTitle(qq422016 qtio422016.Writer) {
	//line templates/circle.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/circle.qtpl:14
	p.StreamTitle(qw422016)
	//line templates/circle.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line templates/circle.qtpl:14
}

//line templates/circle.qtpl:14
func (p *CirclePage) Title() string {
	//line templates/circle.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/circle.qtpl:14
	p.WriteTitle(qb422016)
	//line templates/circle.qtpl:14
	qs422016 := string(qb422016.B)
	//line templates/circle.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/circle.qtpl:14
	return qs422016
//line templates/circle.qtpl:14
}

//line templates/circle.qtpl:16
func (p *CirclePage) StreamContent(qw422016 *qt422016.Writer) {
	//line templates/circle.qtpl:16
	qw422016.N().S(`

`)
	//line templates/circle.qtpl:18
	if len(p.Circle) == 0 {
		//line templates/circle.qtpl:18
		qw422016.N().S(` 
	Circle not found.
`)
		//line templates/circle.qtpl:20
	} else {
		//line templates/circle.qtpl:20
		qw422016.N().S(`
	<article>
		<h1>`)
		//line templates/circle.qtpl:22
		qw422016.E().S(p.Circle[0].Name)
		//line templates/circle.qtpl:22
		qw422016.N().S(`</h1>
		<p>Website: `)
		//line templates/circle.qtpl:23
		qw422016.E().S(p.Circle[0].Website)
		//line templates/circle.qtpl:23
		qw422016.N().S(`</p>
	</article>
	<article>
		<h1>Eroge</h1>
		`)
		//line templates/circle.qtpl:27
		for _, e := range p.Ero {
			//line templates/circle.qtpl:27
			qw422016.N().S(`
		<p><a href="/ero/`)
			//line templates/circle.qtpl:28
			qw422016.N().D(e.ID)
			//line templates/circle.qtpl:28
			qw422016.N().S(`">`)
			//line templates/circle.qtpl:28
			qw422016.E().S(e.Title)
			//line templates/circle.qtpl:28
			qw422016.N().S(`</a></p>
		`)
			//line templates/circle.qtpl:29
		}
		//line templates/circle.qtpl:29
		qw422016.N().S(`
	</article>
`)
		//line templates/circle.qtpl:31
	}
	//line templates/circle.qtpl:31
	qw422016.N().S(` 

`)
//line templates/circle.qtpl:33
}

//line templates/circle.qtpl:33
func (p *CirclePage) WriteContent(qq422016 qtio422016.Writer) {
	//line templates/circle.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/circle.qtpl:33
	p.StreamContent(qw422016)
	//line templates/circle.qtpl:33
	qt422016.ReleaseWriter(qw422016)
//line templates/circle.qtpl:33
}

//line templates/circle.qtpl:33
func (p *CirclePage) Content() string {
	//line templates/circle.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/circle.qtpl:33
	p.WriteContent(qb422016)
	//line templates/circle.qtpl:33
	qs422016 := string(qb422016.B)
	//line templates/circle.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/circle.qtpl:33
	return qs422016
//line templates/circle.qtpl:33
}
