// Code generated by qtc from "ero.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/ero.qtpl:1
package templates

//line templates/ero.qtpl:1
import "github.com/kipukun/sanic_highway/model"

//line templates/ero.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/ero.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/ero.qtpl:4
type ErogePage struct {
	Ero model.Eroge
}

//line templates/ero.qtpl:10
func (p *ErogePage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/ero.qtpl:10
	qw422016.N().S(`
<title>`)
//line templates/ero.qtpl:11
	qw422016.E().S(p.Ero.Filename)
//line templates/ero.qtpl:11
	qw422016.N().S(`</title>
`)
//line templates/ero.qtpl:12
}

//line templates/ero.qtpl:12
func (p *ErogePage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/ero.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/ero.qtpl:12
	p.StreamTitle(qw422016)
//line templates/ero.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line templates/ero.qtpl:12
}

//line templates/ero.qtpl:12
func (p *ErogePage) Title() string {
//line templates/ero.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/ero.qtpl:12
	p.WriteTitle(qb422016)
//line templates/ero.qtpl:12
	qs422016 := string(qb422016.B)
//line templates/ero.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/ero.qtpl:12
	return qs422016
//line templates/ero.qtpl:12
}

//line templates/ero.qtpl:15
func (p *ErogePage) StreamContent(qw422016 *qt422016.Writer) {
//line templates/ero.qtpl:15
	qw422016.N().S(`

<article>
	<h1>`)
//line templates/ero.qtpl:18
	qw422016.E().S(p.Ero.Filename)
//line templates/ero.qtpl:18
	qw422016.N().S(`</h1>
</article>

`)
//line templates/ero.qtpl:21
}

//line templates/ero.qtpl:21
func (p *ErogePage) WriteContent(qq422016 qtio422016.Writer) {
//line templates/ero.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/ero.qtpl:21
	p.StreamContent(qw422016)
//line templates/ero.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line templates/ero.qtpl:21
}

//line templates/ero.qtpl:21
func (p *ErogePage) Content() string {
//line templates/ero.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/ero.qtpl:21
	p.WriteContent(qb422016)
//line templates/ero.qtpl:21
	qs422016 := string(qb422016.B)
//line templates/ero.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/ero.qtpl:21
	return qs422016
//line templates/ero.qtpl:21
}
