// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/index.qtpl:1
package templates

//line templates/index.qtpl:1
import "github.com/kipukun/sanic_highway/model"

//line templates/index.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/index.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/index.qtpl:4
type IndexPage struct {
	EroList             []model.Eroge
	Pagination          [5]int
	Current, Prev, Next int
}

//line templates/index.qtpl:11
func (p *IndexPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/index.qtpl:11
	qw422016.N().S(`
<title>sanic information highway</title>
`)
//line templates/index.qtpl:13
}

//line templates/index.qtpl:13
func (p *IndexPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/index.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/index.qtpl:13
	p.StreamTitle(qw422016)
//line templates/index.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line templates/index.qtpl:13
}

//line templates/index.qtpl:13
func (p *IndexPage) Title() string {
//line templates/index.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/index.qtpl:13
	p.WriteTitle(qb422016)
//line templates/index.qtpl:13
	qs422016 := string(qb422016.B)
//line templates/index.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/index.qtpl:13
	return qs422016
//line templates/index.qtpl:13
}

//line templates/index.qtpl:16
func (p *IndexPage) StreamContent(qw422016 *qt422016.Writer) {
//line templates/index.qtpl:16
	qw422016.N().S(`
<table>
	<tr>
		<th>Title</th>
	</tr>
	`)
//line templates/index.qtpl:21
	for _, ero := range p.EroList {
//line templates/index.qtpl:21
		qw422016.N().S(`
	<tr>
		<td><a href="/ero/`)
//line templates/index.qtpl:23
		qw422016.N().D(ero.ID)
//line templates/index.qtpl:23
		qw422016.N().S(`">`)
//line templates/index.qtpl:23
		qw422016.E().S(ero.Filename)
//line templates/index.qtpl:23
		qw422016.N().S(`</a></td>
	</tr>
	`)
//line templates/index.qtpl:25
	}
//line templates/index.qtpl:25
	qw422016.N().S(`
</table>
<center>
	<div class="pg">
		<a href="/page/`)
//line templates/index.qtpl:29
	qw422016.N().D(p.Prev)
//line templates/index.qtpl:29
	qw422016.N().S(`">◀</a>
		`)
//line templates/index.qtpl:30
	for _, pg := range p.Pagination {
//line templates/index.qtpl:30
		qw422016.N().S(`
			<a href="/page/`)
//line templates/index.qtpl:31
		qw422016.N().D(pg)
//line templates/index.qtpl:31
		qw422016.N().S(`" `)
//line templates/index.qtpl:31
		if pg == p.Current {
//line templates/index.qtpl:31
			qw422016.N().S(` class="current" `)
//line templates/index.qtpl:31
		}
//line templates/index.qtpl:31
		qw422016.N().S(`>`)
//line templates/index.qtpl:31
		qw422016.N().D(pg)
//line templates/index.qtpl:31
		qw422016.N().S(`</a>
		`)
//line templates/index.qtpl:32
	}
//line templates/index.qtpl:32
	qw422016.N().S(`
		<a href="/page/`)
//line templates/index.qtpl:33
	qw422016.N().D(p.Next)
//line templates/index.qtpl:33
	qw422016.N().S(`">▶</a>
</center>
`)
//line templates/index.qtpl:35
}

//line templates/index.qtpl:35
func (p *IndexPage) WriteContent(qq422016 qtio422016.Writer) {
//line templates/index.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/index.qtpl:35
	p.StreamContent(qw422016)
//line templates/index.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line templates/index.qtpl:35
}

//line templates/index.qtpl:35
func (p *IndexPage) Content() string {
//line templates/index.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/index.qtpl:35
	p.WriteContent(qb422016)
//line templates/index.qtpl:35
	qs422016 := string(qb422016.B)
//line templates/index.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/index.qtpl:35
	return qs422016
//line templates/index.qtpl:35
}
