// Code generated by qtc from "layout.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/layout.qtpl:1
package templates

//line templates/layout.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/layout.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/layout.qtpl:2
type Page interface {
//line templates/layout.qtpl:2
	Title() string
//line templates/layout.qtpl:2
	StreamTitle(qw422016 *qt422016.Writer)
//line templates/layout.qtpl:2
	WriteTitle(qq422016 qtio422016.Writer)
//line templates/layout.qtpl:2
	Content() string
//line templates/layout.qtpl:2
	StreamContent(qw422016 *qt422016.Writer)
//line templates/layout.qtpl:2
	WriteContent(qq422016 qtio422016.Writer)
//line templates/layout.qtpl:2
}

//line templates/layout.qtpl:8
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
//line templates/layout.qtpl:8
	qw422016.N().S(`
<!DOCTYPE html>
<html>
	<head>
		`)
//line templates/layout.qtpl:12
	p.StreamTitle(qw422016)
//line templates/layout.qtpl:12
	qw422016.N().S(`
		<link rel="stylesheet" href="/assets/style.css">
	</head>
	<body>
		<header>
			<a src="/" id="logo">Sanic Information Highway</a>
			<nav>
				<ul>
					<li><a href="/">Home</a></li>
					<li><a href="/help">Help</a></li>
					<li><a href="/about">About</a></li>
				</ul>
			</nav>
		</header>
	
		`)
//line templates/layout.qtpl:27
	p.StreamContent(qw422016)
//line templates/layout.qtpl:27
	qw422016.N().S(`
	</body>
</html>
`)
//line templates/layout.qtpl:30
}

//line templates/layout.qtpl:30
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
//line templates/layout.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/layout.qtpl:30
	StreamPageTemplate(qw422016, p)
//line templates/layout.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line templates/layout.qtpl:30
}

//line templates/layout.qtpl:30
func PageTemplate(p Page) string {
//line templates/layout.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/layout.qtpl:30
	WritePageTemplate(qb422016, p)
//line templates/layout.qtpl:30
	qs422016 := string(qb422016.B)
//line templates/layout.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/layout.qtpl:30
	return qs422016
//line templates/layout.qtpl:30
}
